### ISSUE TITLE
a `Revisiting.R` file was committed and merged to `main`

### ISSUE THREAD

**Issue by ernestguevarra** [OxfordIHTM/revisiting-cyclones#7]
@OxfordIHTM/class-2025, in the `main` branch, you will notice that a file called `Revisiting.R` was created, committed, and merged to main. This was from the pull request that @Ellathelight contributed to. The code is roughly correct but I would like us to follow the instructions. @PhyllisTenkorang has a current pull request that is almost there and this pull request will create a `cyclones.R` file which will be our main R script for this project.

While we are waiting for that, I will resolve this issue by removing the `Revisiting.R` file from main through the dev branch. I will tag someone to review my work.

**Comment by ernestguevarra** [comment]
I've made a pull request to fix this issue (#8). I asked @ibrahimAJ-ox to review my pull request.

**Comment by ibrahimAJ-ox** [comment]
LGTM 👍
